# Generated by Django 5.2.5 on 2025-08-28 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trend1', models.CharField(max_length=255)),
                ('trend2', models.CharField(max_length=255)),
                ('trend3', models.CharField(max_length=255)),
                ('trend4', models.CharField(max_length=255)),
                ('trend5', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('run_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
