services:
  - type: worker
    name: scraper-worker
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium-browser chromium-chromedriver
      pip install -r scraper_worker/requirements.txt
    startCommand: python scraper_worker/scraper.py
